controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


api_login_check:
    path: /api/login_check

front_homepage:
    path: /
    controller: App\Controller\FrontController::homepage